### ISSUE TITLE
might want to merge with kotlin-logging?

### ISSUE THREAD

**Issue by oshai** [rs3vans/klogger#1]
I saw you created this repo and thought you might want to "join-forces" and work on my similar repo: https://github.com/MicroUtils/kotlin-logging

**Comment by oshai** [comment]
you are also welcome to discuss it in slack: https://kotlinlang.slack.com/messages/kotlin-logging

**Comment by rs3vans** [comment]
I appreciate the offer. I added this repo as a way for me to commonize code I had already written. I realized that there would probably be other similar implementations out there, but I wanted to go for it anyway ;)

I'll keep mine separate for now.

**Comment by oshai** [comment]
thanks for your reply!
